# backend/remediation-engine/remediation-engine-service/railway.toml
# Railway deployment configuration for Remediation Engine Service
# Maintains all advanced automated remediation capabilities

[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python src/main.py"
healthcheckPath = "/health"
healthcheckTimeout = 15
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[networking]
serviceName = "ai-guardian-remediation-engine"

[env]
ENVIRONMENT = "production"
DEBUG = "false"
PORT = "5003" 